Update windows setup files

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -60,6 +60,13 @@ jobs:
           mkdir installer\artifact
           move artifact\stacksmith.exe installer\artifact\stacksmith.exe
 
+      - name: Check for EXE
+        run: |
+          if (-Not (Test-Path "installer/artifact/stacksmith.exe")) {
+            Write-Error "❌ stacksmith.exe not found!"
+            exit 1
+          }
+
       - name: Build Inno Setup installer
         run: iscc /DMyAppVersion="${{ needs.goreleaser.outputs.version }}" installer/setup.iss
 
